# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/mt8163-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter douglas giza,$(TARGET_DEVICE)),)

endif
